// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import Foundation
import Rswift
import UIKit

/// This `R` struct is code generated, and contains references to static resources.
struct R {
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    private init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `MainVCSettings.json`.
    static let mainVCSettingsJson = FileResource(bundle: _R.hostingBundle, name: "MainVCSettings", pathExtension: "json")
    
    /// `bundle.URLForResource("MainVCSettings", withExtension: "json")`
    static func mainVCSettingsJson(_: Void) -> NSURL? {
      let fileResource = R.file.mainVCSettingsJson
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    private init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    private init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 116 images.
  struct image {
    /// Image `Default`.
    static let `default` = ImageResource(bundle: _R.hostingBundle, name: "Default")
    /// Image `ad_background`.
    static let ad_background = ImageResource(bundle: _R.hostingBundle, name: "ad_background")
    /// Image `avatar_default`.
    static let avatar_default = ImageResource(bundle: _R.hostingBundle, name: "avatar_default")
    /// Image `avatar_default_small`.
    static let avatar_default_small = ImageResource(bundle: _R.hostingBundle, name: "avatar_default_small")
    /// Image `avatar_enterprise_vip`.
    static let avatar_enterprise_vip = ImageResource(bundle: _R.hostingBundle, name: "avatar_enterprise_vip")
    /// Image `avatar_grassroot`.
    static let avatar_grassroot = ImageResource(bundle: _R.hostingBundle, name: "avatar_grassroot")
    /// Image `avatar_vgirl`.
    static let avatar_vgirl = ImageResource(bundle: _R.hostingBundle, name: "avatar_vgirl")
    /// Image `avatar_vip`.
    static let avatar_vip = ImageResource(bundle: _R.hostingBundle, name: "avatar_vip")
    /// Image `Brand Assets`.
    static let brandAssets = ImageResource(bundle: _R.hostingBundle, name: "Brand Assets")
    /// Image `common_button_white_disable`.
    static let common_button_white_disable = ImageResource(bundle: _R.hostingBundle, name: "common_button_white_disable")
    /// Image `common_icon_membership`.
    static let common_icon_membership = ImageResource(bundle: _R.hostingBundle, name: "common_icon_membership")
    /// Image `common_icon_membership_expired`.
    static let common_icon_membership_expired = ImageResource(bundle: _R.hostingBundle, name: "common_icon_membership_expired")
    /// Image `common_icon_membership_level1`.
    static let common_icon_membership_level1 = ImageResource(bundle: _R.hostingBundle, name: "common_icon_membership_level1")
    /// Image `common_icon_membership_level2`.
    static let common_icon_membership_level2 = ImageResource(bundle: _R.hostingBundle, name: "common_icon_membership_level2")
    /// Image `common_icon_membership_level3`.
    static let common_icon_membership_level3 = ImageResource(bundle: _R.hostingBundle, name: "common_icon_membership_level3")
    /// Image `common_icon_membership_level4`.
    static let common_icon_membership_level4 = ImageResource(bundle: _R.hostingBundle, name: "common_icon_membership_level4")
    /// Image `common_icon_membership_level5`.
    static let common_icon_membership_level5 = ImageResource(bundle: _R.hostingBundle, name: "common_icon_membership_level5")
    /// Image `common_icon_membership_level6`.
    static let common_icon_membership_level6 = ImageResource(bundle: _R.hostingBundle, name: "common_icon_membership_level6")
    /// Image `Default-736h_left`.
    static let default736h_left = ImageResource(bundle: _R.hostingBundle, name: "Default-736h_left")
    /// Image `Default-736h_right`.
    static let default736h_right = ImageResource(bundle: _R.hostingBundle, name: "Default-736h_right")
    /// Image `icon`.
    static let icon = ImageResource(bundle: _R.hostingBundle, name: "icon")
    /// Image `icon_os7`.
    static let icon_os7 = ImageResource(bundle: _R.hostingBundle, name: "icon_os7")
    /// Image `navigationbar_arrow_down`.
    static let navigationbar_arrow_down = ImageResource(bundle: _R.hostingBundle, name: "navigationbar_arrow_down")
    /// Image `navigationbar_arrow_up`.
    static let navigationbar_arrow_up = ImageResource(bundle: _R.hostingBundle, name: "navigationbar_arrow_up")
    /// Image `navigationbar_friendattention`.
    static let navigationbar_friendattention = ImageResource(bundle: _R.hostingBundle, name: "navigationbar_friendattention")
    /// Image `navigationbar_friendattention_highlighted`.
    static let navigationbar_friendattention_highlighted = ImageResource(bundle: _R.hostingBundle, name: "navigationbar_friendattention_highlighted")
    /// Image `navigationbar_pop`.
    static let navigationbar_pop = ImageResource(bundle: _R.hostingBundle, name: "navigationbar_pop")
    /// Image `navigationbar_pop_highlighted`.
    static let navigationbar_pop_highlighted = ImageResource(bundle: _R.hostingBundle, name: "navigationbar_pop_highlighted")
    /// Image `new_feature_1`.
    static let new_feature_1 = ImageResource(bundle: _R.hostingBundle, name: "new_feature_1")
    /// Image `new_feature_2`.
    static let new_feature_2 = ImageResource(bundle: _R.hostingBundle, name: "new_feature_2")
    /// Image `new_feature_3`.
    static let new_feature_3 = ImageResource(bundle: _R.hostingBundle, name: "new_feature_3")
    /// Image `new_feature_4`.
    static let new_feature_4 = ImageResource(bundle: _R.hostingBundle, name: "new_feature_4")
    /// Image `new_feature_button`.
    static let new_feature_button = ImageResource(bundle: _R.hostingBundle, name: "new_feature_button")
    /// Image `new_feature_button_highlighted`.
    static let new_feature_button_highlighted = ImageResource(bundle: _R.hostingBundle, name: "new_feature_button_highlighted")
    /// Image `new_feature_finish_button`.
    static let new_feature_finish_button = ImageResource(bundle: _R.hostingBundle, name: "new_feature_finish_button")
    /// Image `new_feature_finish_button_highlighted`.
    static let new_feature_finish_button_highlighted = ImageResource(bundle: _R.hostingBundle, name: "new_feature_finish_button_highlighted")
    /// Image `new_feature_share_false`.
    static let new_feature_share_false = ImageResource(bundle: _R.hostingBundle, name: "new_feature_share_false")
    /// Image `new_feature_share_true`.
    static let new_feature_share_true = ImageResource(bundle: _R.hostingBundle, name: "new_feature_share_true")
    /// Image `popover_background`.
    static let popover_background = ImageResource(bundle: _R.hostingBundle, name: "popover_background")
    /// Image `popover_background_left`.
    static let popover_background_left = ImageResource(bundle: _R.hostingBundle, name: "popover_background_left")
    /// Image `popover_background_right`.
    static let popover_background_right = ImageResource(bundle: _R.hostingBundle, name: "popover_background_right")
    /// Image `preview_like_icon`.
    static let preview_like_icon = ImageResource(bundle: _R.hostingBundle, name: "preview_like_icon")
    /// Image `preview_like_icon_disable`.
    static let preview_like_icon_disable = ImageResource(bundle: _R.hostingBundle, name: "preview_like_icon_disable")
    /// Image `preview_like_icon_highlighted`.
    static let preview_like_icon_highlighted = ImageResource(bundle: _R.hostingBundle, name: "preview_like_icon_highlighted")
    /// Image `qrcode_border`.
    static let qrcode_border = ImageResource(bundle: _R.hostingBundle, name: "qrcode_border")
    /// Image `qrcode_button_background`.
    static let qrcode_button_background = ImageResource(bundle: _R.hostingBundle, name: "qrcode_button_background")
    /// Image `qrcode_embeddedimage_shadow`.
    static let qrcode_embeddedimage_shadow = ImageResource(bundle: _R.hostingBundle, name: "qrcode_embeddedimage_shadow")
    /// Image `qrcode_navigationbar_background`.
    static let qrcode_navigationbar_background = ImageResource(bundle: _R.hostingBundle, name: "qrcode_navigationbar_background")
    /// Image `qrcode_scanline_barcode`.
    static let qrcode_scanline_barcode = ImageResource(bundle: _R.hostingBundle, name: "qrcode_scanline_barcode")
    /// Image `qrcode_scanline_qrcode`.
    static let qrcode_scanline_qrcode = ImageResource(bundle: _R.hostingBundle, name: "qrcode_scanline_qrcode")
    /// Image `qrcode_tabbar_background`.
    static let qrcode_tabbar_background = ImageResource(bundle: _R.hostingBundle, name: "qrcode_tabbar_background")
    /// Image `qrcode_tabbar_icon_barcode`.
    static let qrcode_tabbar_icon_barcode = ImageResource(bundle: _R.hostingBundle, name: "qrcode_tabbar_icon_barcode")
    /// Image `qrcode_tabbar_icon_barcode_highlighted`.
    static let qrcode_tabbar_icon_barcode_highlighted = ImageResource(bundle: _R.hostingBundle, name: "qrcode_tabbar_icon_barcode_highlighted")
    /// Image `qrcode_tabbar_icon_qrcode`.
    static let qrcode_tabbar_icon_qrcode = ImageResource(bundle: _R.hostingBundle, name: "qrcode_tabbar_icon_qrcode")
    /// Image `qrcode_tabbar_icon_qrcode_highlighted`.
    static let qrcode_tabbar_icon_qrcode_highlighted = ImageResource(bundle: _R.hostingBundle, name: "qrcode_tabbar_icon_qrcode_highlighted")
    /// Image `qrcode_tip_background`.
    static let qrcode_tip_background = ImageResource(bundle: _R.hostingBundle, name: "qrcode_tip_background")
    /// Image `tabbar_background`.
    static let tabbar_background = ImageResource(bundle: _R.hostingBundle, name: "tabbar_background")
    /// Image `tabbar_compose_background_icon_add`.
    static let tabbar_compose_background_icon_add = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_background_icon_add")
    /// Image `tabbar_compose_background_icon_close`.
    static let tabbar_compose_background_icon_close = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_background_icon_close")
    /// Image `tabbar_compose_background_icon_return`.
    static let tabbar_compose_background_icon_return = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_background_icon_return")
    /// Image `tabbar_compose_below_background`.
    static let tabbar_compose_below_background = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_below_background")
    /// Image `tabbar_compose_below_button`.
    static let tabbar_compose_below_button = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_below_button")
    /// Image `tabbar_compose_below_button_highlighted`.
    static let tabbar_compose_below_button_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_below_button_highlighted")
    /// Image `tabbar_compose_book`.
    static let tabbar_compose_book = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_book")
    /// Image `tabbar_compose_button`.
    static let tabbar_compose_button = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_button")
    /// Image `tabbar_compose_button_highlighted`.
    static let tabbar_compose_button_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_button_highlighted")
    /// Image `tabbar_compose_camera`.
    static let tabbar_compose_camera = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_camera")
    /// Image `tabbar_compose_delete`.
    static let tabbar_compose_delete = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_delete")
    /// Image `tabbar_compose_envelope`.
    static let tabbar_compose_envelope = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_envelope")
    /// Image `tabbar_compose_friend`.
    static let tabbar_compose_friend = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_friend")
    /// Image `tabbar_compose_icon_add`.
    static let tabbar_compose_icon_add = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_icon_add")
    /// Image `tabbar_compose_icon_add_highlighted`.
    static let tabbar_compose_icon_add_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_icon_add_highlighted")
    /// Image `tabbar_compose_idea`.
    static let tabbar_compose_idea = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_idea")
    /// Image `tabbar_compose_lbs`.
    static let tabbar_compose_lbs = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_lbs")
    /// Image `tabbar_compose_left_button`.
    static let tabbar_compose_left_button = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_left_button")
    /// Image `tabbar_compose_left_button_highlighted`.
    static let tabbar_compose_left_button_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_left_button_highlighted")
    /// Image `tabbar_compose_more`.
    static let tabbar_compose_more = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_more")
    /// Image `tabbar_compose_more_mask`.
    static let tabbar_compose_more_mask = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_more_mask")
    /// Image `tabbar_compose_music`.
    static let tabbar_compose_music = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_music")
    /// Image `tabbar_compose_notloaded`.
    static let tabbar_compose_notloaded = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_notloaded")
    /// Image `tabbar_compose_photo`.
    static let tabbar_compose_photo = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_photo")
    /// Image `tabbar_compose_review`.
    static let tabbar_compose_review = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_review")
    /// Image `tabbar_compose_right_button`.
    static let tabbar_compose_right_button = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_right_button")
    /// Image `tabbar_compose_right_button_highlighted`.
    static let tabbar_compose_right_button_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_right_button_highlighted")
    /// Image `tabbar_compose_shooting`.
    static let tabbar_compose_shooting = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_shooting")
    /// Image `tabbar_compose_transfer`.
    static let tabbar_compose_transfer = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_transfer")
    /// Image `tabbar_compose_video`.
    static let tabbar_compose_video = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_video")
    /// Image `tabbar_compose_voice`.
    static let tabbar_compose_voice = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_voice")
    /// Image `tabbar_compose_wbcamera`.
    static let tabbar_compose_wbcamera = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_wbcamera")
    /// Image `tabbar_compose_weibo`.
    static let tabbar_compose_weibo = ImageResource(bundle: _R.hostingBundle, name: "tabbar_compose_weibo")
    /// Image `tabbar_discover`.
    static let tabbar_discover = ImageResource(bundle: _R.hostingBundle, name: "tabbar_discover")
    /// Image `tabbar_discover_highlighted`.
    static let tabbar_discover_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_discover_highlighted")
    /// Image `tabbar_home`.
    static let tabbar_home = ImageResource(bundle: _R.hostingBundle, name: "tabbar_home")
    /// Image `tabbar_home_highlighted`.
    static let tabbar_home_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_home_highlighted")
    /// Image `tabbar_message_center`.
    static let tabbar_message_center = ImageResource(bundle: _R.hostingBundle, name: "tabbar_message_center")
    /// Image `tabbar_message_center_highlighted`.
    static let tabbar_message_center_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_message_center_highlighted")
    /// Image `tabbar_profile`.
    static let tabbar_profile = ImageResource(bundle: _R.hostingBundle, name: "tabbar_profile")
    /// Image `tabbar_profile_highlighted`.
    static let tabbar_profile_highlighted = ImageResource(bundle: _R.hostingBundle, name: "tabbar_profile_highlighted")
    /// Image `tableview_loading`.
    static let tableview_loading = ImageResource(bundle: _R.hostingBundle, name: "tableview_loading")
    /// Image `tableview_loading@2x副本`.
    static let tableview_loading2x副本 = ImageResource(bundle: _R.hostingBundle, name: "tableview_loading@2x副本")
    /// Image `tableview_pull_refresh`.
    static let tableview_pull_refresh = ImageResource(bundle: _R.hostingBundle, name: "tableview_pull_refresh")
    /// Image `tableview_pull_refresh@2x副本`.
    static let tableview_pull_refresh2x副本 = ImageResource(bundle: _R.hostingBundle, name: "tableview_pull_refresh@2x副本")
    /// Image `timeline_card_bottom_background`.
    static let timeline_card_bottom_background = ImageResource(bundle: _R.hostingBundle, name: "timeline_card_bottom_background")
    /// Image `timeline_card_bottom_line_highlighted`.
    static let timeline_card_bottom_line_highlighted = ImageResource(bundle: _R.hostingBundle, name: "timeline_card_bottom_line_highlighted")
    /// Image `timeline_card_middle_background`.
    static let timeline_card_middle_background = ImageResource(bundle: _R.hostingBundle, name: "timeline_card_middle_background")
    /// Image `timeline_card_middle_background_highlighted`.
    static let timeline_card_middle_background_highlighted = ImageResource(bundle: _R.hostingBundle, name: "timeline_card_middle_background_highlighted")
    /// Image `timeline_icon_comment`.
    static let timeline_icon_comment = ImageResource(bundle: _R.hostingBundle, name: "timeline_icon_comment")
    /// Image `timeline_icon_like`.
    static let timeline_icon_like = ImageResource(bundle: _R.hostingBundle, name: "timeline_icon_like")
    /// Image `timeline_icon_retweet`.
    static let timeline_icon_retweet = ImageResource(bundle: _R.hostingBundle, name: "timeline_icon_retweet")
    /// Image `timeline_icon_unlike`.
    static let timeline_icon_unlike = ImageResource(bundle: _R.hostingBundle, name: "timeline_icon_unlike")
    /// Image `visitordiscover_feed_image_house`.
    static let visitordiscover_feed_image_house = ImageResource(bundle: _R.hostingBundle, name: "visitordiscover_feed_image_house")
    /// Image `visitordiscover_feed_image_smallicon`.
    static let visitordiscover_feed_image_smallicon = ImageResource(bundle: _R.hostingBundle, name: "visitordiscover_feed_image_smallicon")
    /// Image `visitordiscover_feed_mask_smallicon`.
    static let visitordiscover_feed_mask_smallicon = ImageResource(bundle: _R.hostingBundle, name: "visitordiscover_feed_mask_smallicon")
    /// Image `visitordiscover_image_message`.
    static let visitordiscover_image_message = ImageResource(bundle: _R.hostingBundle, name: "visitordiscover_image_message")
    /// Image `visitordiscover_image_profile`.
    static let visitordiscover_image_profile = ImageResource(bundle: _R.hostingBundle, name: "visitordiscover_image_profile")
    /// Image `visitordiscover_signup_logo`.
    static let visitordiscover_signup_logo = ImageResource(bundle: _R.hostingBundle, name: "visitordiscover_signup_logo")
    
    /// `UIImage(named: "Default", bundle: ..., traitCollection: ...)`
    static func `default`(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.`default`, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "ad_background", bundle: ..., traitCollection: ...)`
    static func ad_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.ad_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "avatar_default", bundle: ..., traitCollection: ...)`
    static func avatar_default(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.avatar_default, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "avatar_default_small", bundle: ..., traitCollection: ...)`
    static func avatar_default_small(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.avatar_default_small, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "avatar_enterprise_vip", bundle: ..., traitCollection: ...)`
    static func avatar_enterprise_vip(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.avatar_enterprise_vip, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "avatar_grassroot", bundle: ..., traitCollection: ...)`
    static func avatar_grassroot(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.avatar_grassroot, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "avatar_vgirl", bundle: ..., traitCollection: ...)`
    static func avatar_vgirl(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.avatar_vgirl, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "avatar_vip", bundle: ..., traitCollection: ...)`
    static func avatar_vip(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.avatar_vip, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "Brand Assets", bundle: ..., traitCollection: ...)`
    static func brandAssets(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.brandAssets, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_button_white_disable", bundle: ..., traitCollection: ...)`
    static func common_button_white_disable(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_button_white_disable, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership", bundle: ..., traitCollection: ...)`
    static func common_icon_membership(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_icon_membership, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_expired", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_expired(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_icon_membership_expired, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level1", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_icon_membership_level1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level2", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_icon_membership_level2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level3", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_icon_membership_level3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level4", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_icon_membership_level4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level5", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_icon_membership_level5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level6", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.common_icon_membership_level6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "Default-736h_left", bundle: ..., traitCollection: ...)`
    static func default736h_left(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.default736h_left, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "Default-736h_right", bundle: ..., traitCollection: ...)`
    static func default736h_right(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.default736h_right, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon", bundle: ..., traitCollection: ...)`
    static func icon(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_os7", bundle: ..., traitCollection: ...)`
    static func icon_os7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_os7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_arrow_down", bundle: ..., traitCollection: ...)`
    static func navigationbar_arrow_down(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.navigationbar_arrow_down, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_arrow_up", bundle: ..., traitCollection: ...)`
    static func navigationbar_arrow_up(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.navigationbar_arrow_up, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_friendattention", bundle: ..., traitCollection: ...)`
    static func navigationbar_friendattention(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.navigationbar_friendattention, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_friendattention_highlighted", bundle: ..., traitCollection: ...)`
    static func navigationbar_friendattention_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.navigationbar_friendattention_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_pop", bundle: ..., traitCollection: ...)`
    static func navigationbar_pop(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.navigationbar_pop, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_pop_highlighted", bundle: ..., traitCollection: ...)`
    static func navigationbar_pop_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.navigationbar_pop_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_1", bundle: ..., traitCollection: ...)`
    static func new_feature_1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_2", bundle: ..., traitCollection: ...)`
    static func new_feature_2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_3", bundle: ..., traitCollection: ...)`
    static func new_feature_3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_4", bundle: ..., traitCollection: ...)`
    static func new_feature_4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_button", bundle: ..., traitCollection: ...)`
    static func new_feature_button(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_button, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_button_highlighted", bundle: ..., traitCollection: ...)`
    static func new_feature_button_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_button_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_finish_button", bundle: ..., traitCollection: ...)`
    static func new_feature_finish_button(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_finish_button, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_finish_button_highlighted", bundle: ..., traitCollection: ...)`
    static func new_feature_finish_button_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_finish_button_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_share_false", bundle: ..., traitCollection: ...)`
    static func new_feature_share_false(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_share_false, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "new_feature_share_true", bundle: ..., traitCollection: ...)`
    static func new_feature_share_true(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.new_feature_share_true, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "popover_background", bundle: ..., traitCollection: ...)`
    static func popover_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.popover_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "popover_background_left", bundle: ..., traitCollection: ...)`
    static func popover_background_left(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.popover_background_left, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "popover_background_right", bundle: ..., traitCollection: ...)`
    static func popover_background_right(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.popover_background_right, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "preview_like_icon", bundle: ..., traitCollection: ...)`
    static func preview_like_icon(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.preview_like_icon, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "preview_like_icon_disable", bundle: ..., traitCollection: ...)`
    static func preview_like_icon_disable(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.preview_like_icon_disable, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "preview_like_icon_highlighted", bundle: ..., traitCollection: ...)`
    static func preview_like_icon_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.preview_like_icon_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_border", bundle: ..., traitCollection: ...)`
    static func qrcode_border(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_border, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_button_background", bundle: ..., traitCollection: ...)`
    static func qrcode_button_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_button_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_embeddedimage_shadow", bundle: ..., traitCollection: ...)`
    static func qrcode_embeddedimage_shadow(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_embeddedimage_shadow, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_navigationbar_background", bundle: ..., traitCollection: ...)`
    static func qrcode_navigationbar_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_navigationbar_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_scanline_barcode", bundle: ..., traitCollection: ...)`
    static func qrcode_scanline_barcode(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_scanline_barcode, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_scanline_qrcode", bundle: ..., traitCollection: ...)`
    static func qrcode_scanline_qrcode(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_scanline_qrcode, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_background", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_tabbar_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_barcode", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_barcode(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_tabbar_icon_barcode, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_barcode_highlighted", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_barcode_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_tabbar_icon_barcode_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_qrcode", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_qrcode(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_tabbar_icon_qrcode, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_qrcode_highlighted", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_qrcode_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_tabbar_icon_qrcode_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tip_background", bundle: ..., traitCollection: ...)`
    static func qrcode_tip_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.qrcode_tip_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_background", bundle: ..., traitCollection: ...)`
    static func tabbar_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_background_icon_add", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_background_icon_add(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_background_icon_add, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_background_icon_close", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_background_icon_close(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_background_icon_close, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_background_icon_return", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_background_icon_return(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_background_icon_return, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_below_background", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_below_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_below_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_below_button", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_below_button(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_below_button, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_below_button_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_below_button_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_below_button_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_book", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_book(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_book, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_button", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_button(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_button, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_button_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_button_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_button_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_camera", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_camera(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_camera, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_delete", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_delete(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_delete, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_envelope", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_envelope(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_envelope, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_friend", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_friend(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_friend, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_icon_add", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_icon_add(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_icon_add, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_icon_add_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_icon_add_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_icon_add_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_idea", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_idea(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_idea, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_lbs", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_lbs(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_lbs, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_left_button", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_left_button(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_left_button, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_left_button_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_left_button_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_left_button_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_more", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_more(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_more, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_more_mask", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_more_mask(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_more_mask, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_music", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_music(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_music, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_notloaded", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_notloaded(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_notloaded, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_photo", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_photo(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_photo, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_review", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_review(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_review, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_right_button", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_right_button(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_right_button, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_right_button_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_right_button_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_right_button_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_shooting", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_shooting(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_shooting, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_transfer", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_transfer(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_transfer, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_video", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_video(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_video, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_voice", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_voice(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_voice, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_wbcamera", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_wbcamera(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_wbcamera, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_weibo", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_weibo(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_compose_weibo, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_discover", bundle: ..., traitCollection: ...)`
    static func tabbar_discover(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_discover, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_discover_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_discover_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_discover_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_home", bundle: ..., traitCollection: ...)`
    static func tabbar_home(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_home, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_home_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_home_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_home_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_message_center", bundle: ..., traitCollection: ...)`
    static func tabbar_message_center(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_message_center, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_message_center_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_message_center_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_message_center_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_profile", bundle: ..., traitCollection: ...)`
    static func tabbar_profile(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_profile, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_profile_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_profile_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tabbar_profile_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tableview_loading", bundle: ..., traitCollection: ...)`
    static func tableview_loading(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tableview_loading, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tableview_loading@2x副本", bundle: ..., traitCollection: ...)`
    static func tableview_loading2x副本(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tableview_loading2x副本, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tableview_pull_refresh", bundle: ..., traitCollection: ...)`
    static func tableview_pull_refresh(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tableview_pull_refresh, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "tableview_pull_refresh@2x副本", bundle: ..., traitCollection: ...)`
    static func tableview_pull_refresh2x副本(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.tableview_pull_refresh2x副本, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "timeline_card_bottom_background", bundle: ..., traitCollection: ...)`
    static func timeline_card_bottom_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.timeline_card_bottom_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "timeline_card_bottom_line_highlighted", bundle: ..., traitCollection: ...)`
    static func timeline_card_bottom_line_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.timeline_card_bottom_line_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "timeline_card_middle_background", bundle: ..., traitCollection: ...)`
    static func timeline_card_middle_background(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.timeline_card_middle_background, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "timeline_card_middle_background_highlighted", bundle: ..., traitCollection: ...)`
    static func timeline_card_middle_background_highlighted(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.timeline_card_middle_background_highlighted, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "timeline_icon_comment", bundle: ..., traitCollection: ...)`
    static func timeline_icon_comment(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.timeline_icon_comment, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "timeline_icon_like", bundle: ..., traitCollection: ...)`
    static func timeline_icon_like(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.timeline_icon_like, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "timeline_icon_retweet", bundle: ..., traitCollection: ...)`
    static func timeline_icon_retweet(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.timeline_icon_retweet, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "timeline_icon_unlike", bundle: ..., traitCollection: ...)`
    static func timeline_icon_unlike(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.timeline_icon_unlike, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_image_house", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_image_house(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.visitordiscover_feed_image_house, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_image_smallicon", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_image_smallicon(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.visitordiscover_feed_image_smallicon, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_mask_smallicon", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_mask_smallicon(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.visitordiscover_feed_mask_smallicon, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_image_message", bundle: ..., traitCollection: ...)`
    static func visitordiscover_image_message(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.visitordiscover_image_message, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_image_profile", bundle: ..., traitCollection: ...)`
    static func visitordiscover_image_profile(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.visitordiscover_image_profile, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_signup_logo", bundle: ..., traitCollection: ...)`
    static func visitordiscover_signup_logo(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.visitordiscover_signup_logo, compatibleWithTraitCollection: traitCollection)
    }
    
    private init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 7 nibs.
  struct nib {
    /// Nib `MZCHomePopViewController`.
    static let mZCHomePopViewController = _R.nib._MZCHomePopViewController()
    /// Nib `MZCHomeTableViewCell`.
    static let mZCHomeTableViewCell = _R.nib._MZCHomeTableViewCell()
    /// Nib `MZCLoginViewController`.
    static let mZCLoginViewController = _R.nib._MZCLoginViewController()
    /// Nib `MZCNewVersionCollectionViewCell`.
    static let mZCNewVersionCollectionViewCell = _R.nib._MZCNewVersionCollectionViewCell()
    /// Nib `MZCScanAniView`.
    static let mZCScanAniView = _R.nib._MZCScanAniView()
    /// Nib `MZCScanViewController`.
    static let mZCScanViewController = _R.nib._MZCScanViewController()
    /// Nib `MZCWelcomeViewController`.
    static let mZCWelcomeViewController = _R.nib._MZCWelcomeViewController()
    
    /// `UINib(name: "MZCHomePopViewController", bundle: ...)`
    static func mZCHomePopViewController(_: Void) -> UINib {
      return UINib(resource: R.nib.mZCHomePopViewController)
    }
    
    /// `UINib(name: "MZCHomeTableViewCell", bundle: ...)`
    static func mZCHomeTableViewCell(_: Void) -> UINib {
      return UINib(resource: R.nib.mZCHomeTableViewCell)
    }
    
    /// `UINib(name: "MZCLoginViewController", bundle: ...)`
    static func mZCLoginViewController(_: Void) -> UINib {
      return UINib(resource: R.nib.mZCLoginViewController)
    }
    
    /// `UINib(name: "MZCNewVersionCollectionViewCell", bundle: ...)`
    static func mZCNewVersionCollectionViewCell(_: Void) -> UINib {
      return UINib(resource: R.nib.mZCNewVersionCollectionViewCell)
    }
    
    /// `UINib(name: "MZCScanAniView", bundle: ...)`
    static func mZCScanAniView(_: Void) -> UINib {
      return UINib(resource: R.nib.mZCScanAniView)
    }
    
    /// `UINib(name: "MZCScanViewController", bundle: ...)`
    static func mZCScanViewController(_: Void) -> UINib {
      return UINib(resource: R.nib.mZCScanViewController)
    }
    
    /// `UINib(name: "MZCWelcomeViewController", bundle: ...)`
    static func mZCWelcomeViewController(_: Void) -> UINib {
      return UINib(resource: R.nib.mZCWelcomeViewController)
    }
    
    private init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    private init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    private init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    private init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    private init() {}
  }
  
  private init() {}
}

struct _R {
  static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(NSLocale.init) ?? NSLocale.currentLocale()
  static let hostingBundle = NSBundle(identifier: "MZC.MZCWB") ?? NSBundle.mainBundle()
  
  struct nib {
    struct _MZCHomePopViewController: NibResourceType {
      let bundle = _R.hostingBundle
      let name = "MZCHomePopViewController"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      private init() {}
    }
    
    struct _MZCHomeTableViewCell: NibResourceType {
      let bundle = _R.hostingBundle
      let name = "MZCHomeTableViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> MZCHomeTableViewCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? MZCHomeTableViewCell
      }
      
      private init() {}
    }
    
    struct _MZCLoginViewController: NibResourceType {
      let bundle = _R.hostingBundle
      let name = "MZCLoginViewController"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      private init() {}
    }
    
    struct _MZCNewVersionCollectionViewCell: NibResourceType {
      let bundle = _R.hostingBundle
      let name = "MZCNewVersionCollectionViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> MZCNewVersionCollectionViewCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? MZCNewVersionCollectionViewCell
      }
      
      private init() {}
    }
    
    struct _MZCScanAniView: NibResourceType {
      let bundle = _R.hostingBundle
      let name = "MZCScanAniView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> MZCScanAniView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? MZCScanAniView
      }
      
      private init() {}
    }
    
    struct _MZCScanViewController: NibResourceType {
      let bundle = _R.hostingBundle
      let name = "MZCScanViewController"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      private init() {}
    }
    
    struct _MZCWelcomeViewController: NibResourceType {
      let bundle = _R.hostingBundle
      let name = "MZCWelcomeViewController"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      private init() {}
    }
    
    private init() {}
  }
  
  struct storyboard {
    struct launchScreen: StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIViewController
      
      let bundle = _R.hostingBundle
      let name = "LaunchScreen"
      
      private init() {}
    }
    
    private init() {}
  }
  
  private init() {}
}